[package]
name = "lorelei_simulator"
version = "0.1.0"
description = "Rapidly simulates Pok√©mon Gen 1-2 AI decisions"
license = "GPL-3.0-only"
readme = "../README.md"
edition = "2021"

[dependencies]
safeboy = { version = "0.3.0-beta.1" }
rand = "0.8.5"
